[build]
  publish = "deploy"
  command = "TIMESTAMP=$(date +%s) && mkdir -p deploy && sed \"s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g\" index.html > deploy/index.html && sed \"s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g\" style.css > deploy/style.css && cp app.js _headers _redirects deploy/ && echo \"Deployment with timestamp: $TIMESTAMP\" && ls -la deploy/"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Handle ES6 modules properly
[[headers]]
  for = "/src/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff" 